<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520154545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE album ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE album ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE card ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE card ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE collections ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE collections ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE decklist ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE decklist ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE lists ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE lists ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE scryfall_card ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE scryfall_card ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tournament ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tournament ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tournament_participant ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tournament_participant ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE JSON USING roles::json');
        $this->addSql('ALTER TABLE user_card ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_card ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user_card ALTER album_id DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE album ALTER id SET DEFAULT nextval(\'album_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE album ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE card ALTER id SET DEFAULT nextval(\'card_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE card ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE collections ALTER id SET DEFAULT nextval(\'collections_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE collections ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE decklist ALTER id SET DEFAULT nextval(\'decklist_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE decklist ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE lists ALTER id SET DEFAULT nextval(\'lists_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE lists ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE scryfall_card ALTER id SET DEFAULT nextval(\'scryfall_card_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE scryfall_card ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tournament ALTER id SET DEFAULT nextval(\'tournament_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tournament ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tournament_participant ALTER id SET DEFAULT nextval(\'tournament_participant_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tournament_participant ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE TEXT USING roles::text');
        $this->addSql('ALTER TABLE user_card ALTER id SET DEFAULT nextval(\'user_card_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE user_card ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE user_card ALTER album_id SET DEFAULT 1');
    }
}
