<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525164405 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deck_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, is_sideboard BOOLEAN NOT NULL, decklist_id INT NOT NULL, scryfall_card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF3DCEDF4E9531B ON deck_card (decklist_id)');
        $this->addSql('CREATE INDEX IDX_2AF3DCED329D0CA ON deck_card (scryfall_card_id)');
        $this->addSql('ALTER TABLE deck_card ADD CONSTRAINT FK_2AF3DCEDF4E9531B FOREIGN KEY (decklist_id) REFERENCES decklist (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deck_card ADD CONSTRAINT FK_2AF3DCED329D0CA FOREIGN KEY (scryfall_card_id) REFERENCES scryfall_card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE album DROP CONSTRAINT fk_39986e43a76ed395');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT fk_6c95d41aa76ed395');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT fk_6c95d41a329d0ca');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT fk_6c95d41a1137abcf');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE collections');
        $this->addSql('DROP TABLE user_card');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_39986e43a76ed395 ON album (user_id)');
        $this->addSql('CREATE TABLE collections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, is_foil BOOLEAN NOT NULL, date_added TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, scryfall_card_id INT NOT NULL, album_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6c95d41aa76ed395 ON user_card (user_id)');
        $this->addSql('CREATE INDEX idx_6c95d41a329d0ca ON user_card (scryfall_card_id)');
        $this->addSql('CREATE INDEX idx_6c95d41a1137abcf ON user_card (album_id)');
        $this->addSql('ALTER TABLE album ADD CONSTRAINT fk_39986e43a76ed395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT fk_6c95d41aa76ed395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT fk_6c95d41a329d0ca FOREIGN KEY (scryfall_card_id) REFERENCES scryfall_card (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT fk_6c95d41a1137abcf FOREIGN KEY (album_id) REFERENCES album (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE deck_card DROP CONSTRAINT FK_2AF3DCEDF4E9531B');
        $this->addSql('ALTER TABLE deck_card DROP CONSTRAINT FK_2AF3DCED329D0CA');
        $this->addSql('DROP TABLE deck_card');
    }
}
