<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520173026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_39986E43A76ED395 ON album (user_id)');
        $this->addSql('CREATE TABLE card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE collections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE decklist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, format VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED030EC6A76ED395 ON decklist (user_id)');
        $this->addSql('CREATE TABLE lists (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, format_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE scryfall_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scryfall_id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, mana_cost VARCHAR(255) NOT NULL, image_url VARCHAR(500) NOT NULL, art_crop_url VARCHAR(500) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, card_text TEXT DEFAULT NULL, card_set VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, format VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, max_players INT NOT NULL, invite_code VARCHAR(8) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, current_round INT DEFAULT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD5FB8D961220EA6 ON tournament (creator_id)');
        $this->addSql('CREATE TABLE tournament_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, wins INT NOT NULL, losses INT NOT NULL, position INT DEFAULT NULL, tournament_id INT NOT NULL, user_id INT NOT NULL, decklist_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C4BB35B33D1A3E7 ON tournament_participant (tournament_id)');
        $this->addSql('CREATE INDEX IDX_5C4BB35BA76ED395 ON tournament_participant (user_id)');
        $this->addSql('CREATE INDEX IDX_5C4BB35BF4E9531B ON tournament_participant (decklist_id)');
        $this->addSql('CREATE TABLE user_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, is_foil BOOLEAN NOT NULL, date_added TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, scryfall_card_id INT NOT NULL, album_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C95D41AA76ED395 ON user_card (user_id)');
        $this->addSql('CREATE INDEX IDX_6C95D41A329D0CA ON user_card (scryfall_card_id)');
        $this->addSql('CREATE INDEX IDX_6C95D41A1137ABCF ON user_card (album_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, nickname VARCHAR(255) DEFAULT NULL, profile_picture_filename VARCHAR(500) DEFAULT NULL, profile_art_url VARCHAR(500) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "users" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_NICKNAME ON "users" (nickname)');
        $this->addSql('ALTER TABLE album ADD CONSTRAINT FK_39986E43A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE decklist ADD CONSTRAINT FK_ED030EC6A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D961220EA6 FOREIGN KEY (creator_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_participant ADD CONSTRAINT FK_5C4BB35B33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_participant ADD CONSTRAINT FK_5C4BB35BA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tournament_participant ADD CONSTRAINT FK_5C4BB35BF4E9531B FOREIGN KEY (decklist_id) REFERENCES decklist (id)');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41AA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41A329D0CA FOREIGN KEY (scryfall_card_id) REFERENCES scryfall_card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_card ADD CONSTRAINT FK_6C95D41A1137ABCF FOREIGN KEY (album_id) REFERENCES album (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE album DROP CONSTRAINT FK_39986E43A76ED395');
        $this->addSql('ALTER TABLE decklist DROP CONSTRAINT FK_ED030EC6A76ED395');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D961220EA6');
        $this->addSql('ALTER TABLE tournament_participant DROP CONSTRAINT FK_5C4BB35B33D1A3E7');
        $this->addSql('ALTER TABLE tournament_participant DROP CONSTRAINT FK_5C4BB35BA76ED395');
        $this->addSql('ALTER TABLE tournament_participant DROP CONSTRAINT FK_5C4BB35BF4E9531B');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41AA76ED395');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41A329D0CA');
        $this->addSql('ALTER TABLE user_card DROP CONSTRAINT FK_6C95D41A1137ABCF');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE card');
        $this->addSql('DROP TABLE collections');
        $this->addSql('DROP TABLE decklist');
        $this->addSql('DROP TABLE lists');
        $this->addSql('DROP TABLE scryfall_card');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE tournament_participant');
        $this->addSql('DROP TABLE user_card');
        $this->addSql('DROP TABLE "users"');
    }
}
